import replicate
import requests
from PIL import Image
import os
import numpy as np

# export REPLICATE_API_TOKEN=#######################################

##########################################################################################################################
def image_generator(image, target, manipulation):
    output = replicate.run('orpatashnik/styleclip:7af9a66f36f97fee2fece7dcc927551a951f0022cbdd23747b9212f23fc17021',
                           input={'input': open(image, "rb"), # user input
                                  'neutral': 'a face', # default
                                  'target': target, # user input
                                  'manipulation_strength': manipulation, # manipulation_strength
                                  'disentanglement_threshold': 0.15 # default
                                 }
                          )
    return output # link generated by replicate
##########################################################################################################################

##########################################################################################################################
def save_image(link, manipulation):
    img_data = requests.get(link).content
    output_image_path = str(manipulation) + '.jpg'
    with open(output_image_path, 'wb') as handler:
        handler.write(img_data)
    return output_image_path

##########################################################################################################################

def style_clip(original_image_path, target, manipulation_strength):

    # Create a output image based on image input, target input and manipulation strength variation
    ##########################################################################################################################
    for manipulation in manipulation_strength:
        print(manipulation)
        output = image_generator(image=original_image_path, target=target, manipulation=manipulation)
        save_image(link=output, manipulation=manipulation)
    ##########################################################################################################################
